[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Worst Server Ever Docs"
authors = [{name = "DraconicDragon3, Mdog504, Insert-usernamehere, Jura", email = "graziella@lumache"}]
dynamic = ["version", "description"]
